spring:
  #Database
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: 123456
    url: jdbc:sqlserver://localhost;databaseName=Lab231
    username: sa
  #Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #Thymeleaf
  thymeleaf:
    cache: false

app:
  page-name: The Coffee Shop
  author: Khang Vo
  map: <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3833.8070869234566!2d108.16825551485863!3d16.07549748887703!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x314218e6c28f0c47%3A0xc38eebeacb9a7963!2zMTIzIE5ndXnhu4VuIFRo4buLIFRo4bqtcCwgVGhhbmggS2jDqiBUw6J5LCBMacOqbiBDaGnhu4N1LCDEkMOgIE7hurVuZw!5e0!3m2!1svi!2s!4v1602919541272!5m2!1svi!2s" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>